/* Generated By:JavaCC: Do not edit this line. AnalyzerConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int classToken = 5;
  /** RegularExpression Id. */
  int publicToken = 6;
  /** RegularExpression Id. */
  int staticToken = 7;
  /** RegularExpression Id. */
  int voidToken = 8;
  /** RegularExpression Id. */
  int mainToken = 9;
  /** RegularExpression Id. */
  int stringToken = 10;
  /** RegularExpression Id. */
  int returnToken = 11;
  /** RegularExpression Id. */
  int extendsToken = 12;
  /** RegularExpression Id. */
  int intToken = 13;
  /** RegularExpression Id. */
  int booleanToken = 14;
  /** RegularExpression Id. */
  int floatToken = 15;
  /** RegularExpression Id. */
  int ifToken = 16;
  /** RegularExpression Id. */
  int elseToken = 17;
  /** RegularExpression Id. */
  int whileToken = 18;
  /** RegularExpression Id. */
  int trueToken = 19;
  /** RegularExpression Id. */
  int falseToken = 20;
  /** RegularExpression Id. */
  int thisToken = 21;
  /** RegularExpression Id. */
  int newToken = 22;
  /** RegularExpression Id. */
  int soutToken = 23;
  /** RegularExpression Id. */
  int openedBraceToken = 24;
  /** RegularExpression Id. */
  int closedBraceToken = 25;
  /** RegularExpression Id. */
  int openedParenthesisToken = 26;
  /** RegularExpression Id. */
  int closedParenthesisToken = 27;
  /** RegularExpression Id. */
  int openedCurlyBracketsToken = 28;
  /** RegularExpression Id. */
  int closedCurlyBracketsToken = 29;
  /** RegularExpression Id. */
  int semiColonToken = 30;
  /** RegularExpression Id. */
  int equalsToken = 31;
  /** RegularExpression Id. */
  int andToken = 32;
  /** RegularExpression Id. */
  int orToken = 33;
  /** RegularExpression Id. */
  int lessThanToken = 34;
  /** RegularExpression Id. */
  int moreThanToken = 35;
  /** RegularExpression Id. */
  int lessOrEqualThanToken = 36;
  /** RegularExpression Id. */
  int moreOrEqualThanToken = 37;
  /** RegularExpression Id. */
  int plusToken = 38;
  /** RegularExpression Id. */
  int minusToken = 39;
  /** RegularExpression Id. */
  int multiplicationToken = 40;
  /** RegularExpression Id. */
  int divisionToken = 41;
  /** RegularExpression Id. */
  int dotToken = 42;
  /** RegularExpression Id. */
  int notToken = 43;
  /** RegularExpression Id. */
  int idToken = 44;
  /** RegularExpression Id. */
  int realConstToken = 45;
  /** RegularExpression Id. */
  int errorSymbNotIdent = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"return\"",
    "\"extends\"",
    "\"int\"",
    "\"boolean\"",
    "\"float\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"System.out.println\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"|\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\".\"",
    "\"!\"",
    "<idToken>",
    "<realConstToken>",
    "<errorSymbNotIdent>",
  };

}
